### ISSUE TITLE
Icons - Unicode

### ISSUE THREAD

**Issue by alexsomeoddpilot** [SomeoddpilotInc/SopUI#14]
Unicode icons

**Comment by krispy1298** [comment]
ive noticed unicode characters display differently between desktop and android tablet. not sure how many other situations show differently or if a simple font family declaration would fix it, but this would need more testing.

**Comment by alexsomeoddpilot** [comment]
Something that might also be helpful instead would just be a cheat sheet of the escape codes and their corresponding glyphs.

| glyph | name | escape code |
| --- | --- | --- |
| ✓ | Checkmark | \2713 |
| ► | Right pointing triangle | \25ba |

**Comment by alexsomeoddpilot** [comment]
We’ve decided that this task is too huge and doesn’t have much benefit over searching for the character codes through other means, a la copypastecharacter.com.
