### ISSUE TITLE
Icons - Social

### ISSUE THREAD

**Issue by alexsomeoddpilot** [SomeoddpilotInc/SopUI#15]

**Comment by krispy1298** [comment]
any others you think we should include?

![screen shot 2015-04-27 at 5 26 20 pm](https://cloud.githubusercontent.com/assets/5984567/7359317/98cd6c3e-ed02-11e4-9e7f-e9fad8d1508c.png)

**Comment by alexsomeoddpilot** [comment]
I would also include some alternates. Sometimes we use the knocked out versions of Facebook and Instagram.

![screen shot 2015-04-28 at 8 18 24 am](https://cloud.githubusercontent.com/assets/5588412/7370355/3a069bee-ed7f-11e4-8346-59625505c8f0.png)
![screen shot 2015-04-28 at 8 18 32 am](https://cloud.githubusercontent.com/assets/5588412/7370356/3a06f832-ed7f-11e4-80f5-da7ff39abc32.png)

**Comment by alexsomeoddpilot** [comment]
Covered by PR #21
